---

- name: common setup for all nodes
  hosts: all
  gather_facts: True
  remote_user: root

  roles:
    - common

##############################
##############################

- name: cluster setup
  hosts: master:workers
  gather_facts: True
  remote_user: root

  environment:
    http_proxy: '{{ http_proxy }}'
    https_proxy: '{{ https_proxy }}'

  roles:
    - install_hadoop
    - install_spark

##############################
##############################

- name: prepare Zeppelin instance
  hosts: zeppelin
  remote_user: root

  environment:
    http_proxy: '{{ http_proxy }}'
    https_proxy: '{{ https_proxy }}'

  vars:
    docker_http_proxy: "{{ ansible_env.http_proxy|default('') }}"

  roles:
    - angstwad.docker_ubuntu
    - install_zeppelin

