---
spark_ver : '2.2.0'
spark_hadoop_ver : hadoop2.7

spark_mirror_url : https://archive.apache.org/dist/spark

spark_checksums:
  '2.2.0': sha256:97fd2cc58e08975d9c4e4ffa8d7f8012c0ac2792bcd9945ce2a561cf937aebcc
  # http://apache.claz.org/spark/spark-2.2.1/spark-2.2.1-bin-hadoop2.7.tgz
  '2.2.1': sha256:79fb8285546670923a66082324bf56e99a7201476a52dea908804ddfa04f16c8

spark_parent_dir: /usr/local
spark_timeout: 10

spark_name: spark-{{spark_ver}}
spark_hadoop_name: '{{spark_name}}-bin-{{spark_hadoop_ver}}'
spark_tgz : '{{spark_hadoop_name}}.tgz'

spark_url : '{{spark_mirror_url}}/{{spark_name}}/{{spark_tgz}}'
spark_checksum: '{{spark_checksums[spark_ver]}}'

spark_target_dir : '{{spark_parent_dir}}/{{spark_hadoop_name}}'
spark_link_dir: '{{spark_parent_dir}}/spark'